In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 1 (Jun 2022 - May 2023)\BTU_GEO_hourly\48190969_BTU_GEO_hourly.csv"
df_main = pd.read_csv(path)

In [6]:
df_main.head()

,Timestamp,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
0,2022-06-01 00:00:00-04:00,75.040726,70.522681,74.785046,70.368942,78.455754,79.778523,0.0,0.0,0.0,0.0,0.000579,0.001995
1,2022-06-01 01:00:00-04:00,74.656820,70.058893,74.418943,69.915249,77.989847,79.297036,0.0,0.0,0.0,0.0,0.000000,0.000000
2,2022-06-01 02:00:00-04:00,74.357355,69.788286,74.115027,69.660119,77.602630,78.886805,0.0,0.0,0.0,0.0,0.000000,0.000000
3,2022-06-01 03:00:00-04:00,74.360408,70.194095,74.091848,70.112857,77.500555,78.777793,0.0,0.0,0.0,0.0,0.000000,0.000000
4,2022-06-01 04:00:00-04:00,74.470037,70.652708,74.208688,70.614932,77.518523,78.772827,0.0,0.0,0.0,0.0,0.000000,0.000000

In [9]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Timestamp                      8760 non-null   object
 1   BTU2(Gwell_L)_ReturnT (F)      8760 non-null   float64
 2   BTU2(Gwell_L)_SupplyT (F)      8760 non-null   float64
 3   BTU3(Gwell_R)_ReturnT (F)      8760 non-null   float64
 4   BTU3(Gwell_R)_SupplyT (F)      8760 non-null   float64
 5   BTU4(Gwell_Com)_ReturnT (F)    8760 non-null   float64
 6   BTU4(Gwell_Com)_SupplyT (F)    8760 non-null   float64
 7   BTU2(Gwell_L)_energy (BTUs)    8760 non-null   float64
 8   BTU2(Gwell_L)_flow (GPM)       8760 non-null   float64
 9   BTU3(Gwell_R)_energy (BTUs)    8760 non-null   float64
 10  BTU3(Gwell_R)_flow (GPM)       8760 non-null   float64
 11  BTU4(Gwell_Com)_energy (BTUs)  8760 non-null   float64
 12  BTU4(Gwell_Com)_flow (GPM)     8760 non-null   float64
dtypes: float64(12), object(1)
memory usage: 889.8+ KB

In [11]:
df_main.isna().sum()

Timestamp                        0
BTU2(Gwell_L)_ReturnT (F)        0
BTU2(Gwell_L)_SupplyT (F)        0
BTU3(Gwell_R)_ReturnT (F)        0
BTU3(Gwell_R)_SupplyT (F)        0
BTU4(Gwell_Com)_ReturnT (F)      0
BTU4(Gwell_Com)_SupplyT (F)      0
BTU2(Gwell_L)_energy (BTUs)      0
BTU2(Gwell_L)_flow (GPM)         0
BTU3(Gwell_R)_energy (BTUs)      0
BTU3(Gwell_R)_flow (GPM)         0
BTU4(Gwell_Com)_energy (BTUs)    0
BTU4(Gwell_Com)_flow (GPM)       0
dtype: int64

In [13]:
df_main.value_counts().sum()

np.int64(8760)

In [15]:
zero_counts = (df_main == 0).sum()
zero_counts

Timestamp                           0
BTU2(Gwell_L)_ReturnT (F)           0
BTU2(Gwell_L)_SupplyT (F)           0
BTU3(Gwell_R)_ReturnT (F)           0
BTU3(Gwell_R)_SupplyT (F)           0
BTU4(Gwell_Com)_ReturnT (F)         0
BTU4(Gwell_Com)_SupplyT (F)         0
BTU2(Gwell_L)_energy (BTUs)      3722
BTU2(Gwell_L)_flow (GPM)         3720
BTU3(Gwell_R)_energy (BTUs)      3722
BTU3(Gwell_R)_flow (GPM)         3720
BTU4(Gwell_Com)_energy (BTUs)    3574
BTU4(Gwell_Com)_flow (GPM)       3687
dtype: int64

In [16]:
df_main['Timestamp'] = pd.to_datetime(df_main['Timestamp'])

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_11512\569357206.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df_main['Timestamp'] = pd.to_datetime(df_main['Timestamp'])

In [18]:
df_main.head()

,Timestamp,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
0,2022-06-01 00:00:00-04:00,75.040726,70.522681,74.785046,70.368942,78.455754,79.778523,0.0,0.0,0.0,0.0,0.000579,0.001995
1,2022-06-01 01:00:00-04:00,74.656820,70.058893,74.418943,69.915249,77.989847,79.297036,0.0,0.0,0.0,0.0,0.000000,0.000000
2,2022-06-01 02:00:00-04:00,74.357355,69.788286,74.115027,69.660119,77.602630,78.886805,0.0,0.0,0.0,0.0,0.000000,0.000000
3,2022-06-01 03:00:00-04:00,74.360408,70.194095,74.091848,70.112857,77.500555,78.777793,0.0,0.0,0.0,0.0,0.000000,0.000000
4,2022-06-01 04:00:00-04:00,74.470037,70.652708,74.208688,70.614932,77.518523,78.772827,0.0,0.0,0.0,0.0,0.000000,0.000000

In [19]:
df_main = df_main.set_index('Timestamp')

In [21]:
df_main

,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
Timestamp,,,,,,,,,,,,
2022-06-01 00:00:00-04:00,75.040726,70.522681,74.785046,70.368942,78.455754,79.778523,0.0,0.0,0.0,0.0,0.000579,0.001995
2022-06-01 01:00:00-04:00,74.656820,70.058893,74.418943,69.915249,77.989847,79.297036,0.0,0.0,0.0,0.0,0.000000,0.000000
2022-06-01 02:00:00-04:00,74.357355,69.788286,74.115027,69.660119,77.602630,78.886805,0.0,0.0,0.0,0.0,0.000000,0.000000
2022-06-01 03:00:00-04:00,74.360408,70.194095,74.091848,70.112857,77.500555,78.777793,0.0,0.0,0.0,0.0,0.000000,0.000000
2022-06-01 04:00:00-04:00,74.470037,70.652708,74.208688,70.614932,77.518523,78.772827,0.0,0.0,0.0,0.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-05-31 19:00:00-04:00,73.439383,69.975626,73.347141,69.946995,76.520778,77.328809,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 20:00:00-04:00,73.540788,70.044299,73.433754,70.007668,76.616079,77.426735,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 21:00:00-04:00,73.629954,70.101324,73.506638,70.068226,76.679861,77.480990,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 22:00:00-04:00,73.668879,70.138545,73.551542,70.102510,76.694057,77.494696,0.0,0.0,0.0,0.0,0.000000,0.000000
2023-05-31 23:00:00-04:00,73.676779,70.161604,73.557531,70.125401,76.670259,77.466775,0.0,0.0,0.0,0.0,0.000000,0.000000

In [22]:
temp_cols = [
    "BTU2(Gwell_L)_ReturnT (F)", "BTU2(Gwell_L)_SupplyT (F)",
    "BTU3(Gwell_R)_ReturnT (F)", "BTU3(Gwell_R)_SupplyT (F)",
    "BTU4(Gwell_Com)_ReturnT (F)", "BTU4(Gwell_Com)_SupplyT (F)"
]

energy_cols = [
    "BTU2(Gwell_L)_energy (BTUs)",
    "BTU3(Gwell_R)_energy (BTUs)",
    "BTU4(Gwell_Com)_energy (BTUs)"
]

flow_cols = [
    "BTU2(Gwell_L)_flow (GPM)",
    "BTU3(Gwell_R)_flow (GPM)",
    "BTU4(Gwell_Com)_flow (GPM)"
]

In [ ]:
for col in df_main.columns:
    if col in temp_cols:
        df_main.loc[((df_main[col] < 40) | (df_main[col] > 120)), col] = np.nan

In [25]:
for col in df_main.columns:
    if col in energy_cols or col in temp_cols:
        df_main.loc[df_main[col] < 0, col] = np.nan

In [26]:
df_main.isna().sum()

BTU2(Gwell_L)_ReturnT (F)        0
BTU2(Gwell_L)_SupplyT (F)        0
BTU3(Gwell_R)_ReturnT (F)        0
BTU3(Gwell_R)_SupplyT (F)        0
BTU4(Gwell_Com)_ReturnT (F)      3
BTU4(Gwell_Com)_SupplyT (F)      0
BTU2(Gwell_L)_energy (BTUs)      0
BTU2(Gwell_L)_flow (GPM)         0
BTU3(Gwell_R)_energy (BTUs)      0
BTU3(Gwell_R)_flow (GPM)         0
BTU4(Gwell_Com)_energy (BTUs)    0
BTU4(Gwell_Com)_flow (GPM)       0
dtype: int64

In [27]:
df_main = df_main.sort_index()

In [28]:
field = 'BTU4(Gwell_Com)_ReturnT (F)'
df_main[field] = df_main[field].interpolate(limit=2)

In [29]:
df_main.isna().sum()

BTU2(Gwell_L)_ReturnT (F)        0
BTU2(Gwell_L)_SupplyT (F)        0
BTU3(Gwell_R)_ReturnT (F)        0
BTU3(Gwell_R)_SupplyT (F)        0
BTU4(Gwell_Com)_ReturnT (F)      0
BTU4(Gwell_Com)_SupplyT (F)      0
BTU2(Gwell_L)_energy (BTUs)      0
BTU2(Gwell_L)_flow (GPM)         0
BTU3(Gwell_R)_energy (BTUs)      0
BTU3(Gwell_R)_flow (GPM)         0
BTU4(Gwell_Com)_energy (BTUs)    0
BTU4(Gwell_Com)_flow (GPM)       0
dtype: int64

In [30]:
scaler = StandardScaler()
df_scaled = df_main
df_scaled[temp_cols+energy_cols+flow_cols] = scaler.fit_transform(df_scaled[temp_cols + energy_cols + flow_cols])

In [31]:
df_scaled.head()

,BTU2(Gwell_L)_ReturnT (F),BTU2(Gwell_L)_SupplyT (F),BTU3(Gwell_R)_ReturnT (F),BTU3(Gwell_R)_SupplyT (F),BTU4(Gwell_Com)_ReturnT (F),BTU4(Gwell_Com)_SupplyT (F),BTU2(Gwell_L)_energy (BTUs),BTU2(Gwell_L)_flow (GPM),BTU3(Gwell_R)_energy (BTUs),BTU3(Gwell_R)_flow (GPM),BTU4(Gwell_Com)_energy (BTUs),BTU4(Gwell_Com)_flow (GPM)
Timestamp,,,,,,,,,,,,
2022-06-01 00:00:00-04:00,1.140578,1.007840,1.123263,0.988839,1.191622,1.299071,-0.859438,-1.099479,-0.912963,-1.094373,-0.916230,-1.098305
2022-06-01 01:00:00-04:00,1.103632,0.955303,1.088484,0.937113,1.153639,1.258188,-0.859438,-1.099479,-0.912963,-1.094373,-0.916339,-1.098665
2022-06-01 02:00:00-04:00,1.074811,0.924649,1.059613,0.908026,1.122072,1.223355,-0.859438,-1.099479,-0.912963,-1.094373,-0.916339,-1.098665
2022-06-01 03:00:00-04:00,1.075105,0.970618,1.057411,0.959643,1.113750,1.214099,-0.859438,-1.099479,-0.912963,-1.094373,-0.916339,-1.098665
2022-06-01 04:00:00-04:00,1.085656,1.022569,1.068511,1.016885,1.115215,1.213678,-0.859438,-1.099479,-0.912963,-1.094373,-0.916339,-1.098665